- website/build.tsx
> docs(typo): Github => GitHub

- examples/hackernews/README.md
- examples/hackernews/package.json
- examples/todomvc-ts/README.md
- examples/todomvc-ts/package.json
- examples/todomvc/README.md
- examples/todomvc/package.json
I've added a start script so that the examples (which have parcel as a devDependency) can be run locally.
> chore | Add start script for running the examples via parcel

- src/__tests__/html.tsx
- src/html.ts
Hello @brainkim 
This library is awesome and creative, thanks for this !
I'll try to understand it in the next few days.
Here is my first PR on html attrs, thanks.
> Fix/htmlattrs - escapeText styles also and handles false attrs correctly

- package.json
closes https://github.com/bikeshaving/crank/issues/93
> making event-target-shim a dependency

- CHANGELOG.md
- package.json
- src/__tests__/index.tsx
- src/index.ts
> back out of separate commit optimizations

- src/__tests__/components.tsx
- src/__tests__/events.tsx
- src/__tests__/html.tsx
- src/__tests__/races.tsx
- src/dom.ts
- src/html.ts
- src/index.ts
More tweaks before 0.2.0. Fixes Suspense stuff for real, adds comments and some more tests.
> LAST LAST LAST PUSH

- package.json
- rollup.config.js
- src/index.ts
- yarn.lock
Fixes #130 and might be a tiny bit faster.
> Some tweaks

- src/__tests__/errors.tsx
- src/index.ts
Fixes some edge cases and makes errored components slightly more recoverable
> Improve error handling and recovery

- examples/async-generator/yarn.lock
- examples/hackernews/yarn.lock
- examples/simple/yarn.lock
- examples/todomvc-ts/yarn.lock
- examples/todomvc/yarn.lock
- src/__tests__/components.tsx
- src/index.ts
- website/yarn.lock
- yarn.lock
> Some fixes

- src/__tests__/cascades.tsx
- src/__tests__/cleanup.tsx
- src/__tests__/components.tsx
- src/__tests__/copy.tsx
- src/__tests__/dom.tsx
- src/__tests__/errors.tsx
- src/__tests__/keys.tsx
- src/__tests__/provisions.tsx
- src/__tests__/races.tsx
- src/__tests__/refs.tsx
- src/__tests__/reuse.tsx
- src/__tests__/schedule.tsx
- src/__tests__/suspense.tsx
- src/__tests__/svg.tsx
- src/crank.ts
> Fix async generator bugs

- src/__tests__/events.tsx
- src/crank.ts
- src/dom.ts
> Small tweaks and fixes

- src/__tests__/html.tsx
- src/html.ts
> Fix SSR style rendering

- src/__tests__/complete.tsx
- src/crank.ts
> add a complete method to contexts

- src/__tests__/static.tsx
- src/crank.ts
> Implement `crank-static` prop

- .gitignore
- CHANGELOG.md
- jest.config.cjs
- package.json
- rollup.config.js
- src/__tests__/cascades.tsx
- src/__tests__/schedule.tsx
- src/crank.ts
- src/dom.ts
- yarn.lock
TODO: consider using npm org b9g instead of bikeshaving as a quality of life improvement
> 0.4 beta tweaks

- src/__tests__/html.tsx
- src/html.ts
> Fix null/undefined in className property for HTML renderer

- src/crank.ts
Fixes https://github.com/bikeshaving/crank/issues/236
The `addEventListener`, `removeEventListener`, `dispatchEvent` seem to be leaked when using vite, causing runtime errors.
> Fix eventtarget errors

- src/crank.ts
- test/cleanup.tsx
- test/errors.tsx
> Small fixes

- src/dom.ts
- test/dom.tsx
Fix for #257 
Added a test to highlight the issue.
My fix might be heavy handed, so totally open to feedback.
> Set node property even when equal to default prop value

- src/crank.ts
- test/keys.tsx
> fix keyed elements disappearing

- README.md
This was a relatively low effort change via Claude that I think would help if folks land on this readme. I was trying to figure out why I should care about Crank and this description has me caring about it and wanting to try it.
> Why Crank?

- docs/guides/10-custom-renderers.md
- src/crank.ts
- website/src/styles/client.css
- website/src/views/home.ts
https://github.com/bikeshaving/crank/issues/305
> Website 0.7
